### ISSUE TITLE
Le scrapper ne fonctionnait pas correctement

### ISSUE THREAD

**Issue by 8area8** [OpenClassrooms-Student-Center/demarrez_votre_projet_avec_python#2]
(je parlerai français par facilité :) ).

Bonjour,

j'ai eu beaucoup de problème avec le scrapper.
Je suis sous windows 10, python 3.6 (en x64 et x32 bits), et j'utilise le shell 'Bash' de 'git for windows'.

- lors de l'installation du package, twisted ne s'installe pas correctement. Sous windows, il demande un librairie C++ de visual studio 2014 (ce qui prend quand même pas mal de temps!).
- Ensuite, j'ai eu des problèmes d'encoding lors de l'installation de twisted (qui venaient finalement de 'cmder' mais après un test directement dans 'Bash' tout s'est bien déroulé).

- enfin et surtout, il semblerait (d'après mes différentes recherches) que le format json convertit en unicode et non en UTF8 donc à chaque 'dump' de la part du scrapper, je me retrouvait avec des noms déformés lorsqu'il y avait des accents.
La solution est d'ajouter une config au scrapper (on peut aussi définir un fichier de config global mais mon niveau est pas assez élevé pour comprendre comment faire):
```python
# -*- coding: utf8 -*-

import scrapy


class BlogSpider(scrapy.Spider):
    """spider class."""
    name = 'characterspider'
    custom_settings = {'FEED_EXPORT_ENCODING': 'utf-8'}  # ici la bonne configuration pour importer dans un fichier json

    start_urls = ['https://fr.wikipedia.org/wiki/Cat%C3%A9gorie:Personnage_d\'animation']

    def parse(self, response):
        for link in response.css('div#mw-pages div.mw-content-ltr li'):
            yield {'character': link.css('a ::text').extract_first()}
```

Voila c'était une bonne galère pour un tuto de bases en python, si des explications peuvent être ajoutés pour ne pas perdre les nouveaux ce pourrait être bien.
Merci en tout cas pour cet apprentissage.

**Comment by Teshell** [comment]
Bonjour @8area8  ! Pour installer Twisted vous devez vous rendre sur cette page: https://www.lfd.uci.edu/~gohlke/pythonlibs/ et rechercher Twisted, vous téléchargez cette version Twisted‑18.4.0‑cp36‑cp36m‑win32.whl une fois le téléchargement terminé, ouvrez cmd et exécutez cette commande: pip install le nom du fichier téléchargé avec son chemin absolu, après vous pouvez faire un pip install scrapy ça devrait marcher. Mais avant d'utilisez Scrapy vous devez installer ce module pypiwin32 en faisant pip install pypiwin32
Mais je suppose que depuis ce temps vous avez du trouver le problème, en tout cas bon courage !

**Comment by 8area8** [comment]
Oui en effet, je l'avais même trouvé avant d'avoir crée l'issue, c'était surtout pour moi un moyen de vous faire part de mes remarques.

Bonne journée !
